apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qsm-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  ingressClassName: nginx
  rules:
    - host: qsm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qsm-api
                port:
                  number: 80
