apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.example.yaml
  - deployment-model.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - service-model.yaml
  - service.yaml
  - hpa-api.yaml
  - hpa-worker.yaml
  - pdb-api.yaml
  - ingress.yaml
  - networkpolicy.yaml
